name: Deploy

on:
  release:
    types: [published]

jobs:
  make:
    name: Make
    runs-on: windows-latest
    environment: Compile
    steps:
      - name: 📦 Prepate Git Repo
        uses: actions/checkout@v2

      - name: 📦 Install npm
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
          architecture: x64

      - name: 📦 Package Executable
        run: |
          npm run prepare
          npm run make

      - name: 📦 Zip Release
        uses: TheDoctor0/zip-release@0.4.1
        with:
          directory: out/
          filename: desktop-flick-win32-x64.zip
          path: desktop-flick-win32-x64

      - name: 🚀 Deploy Installer to Releases
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'out/make/**.exe; out/make/**.zip; out/**.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}