name: Deploy

on:
  release:
    types: [published]

jobs:
  make:
    name: Make
    runs-on: windows-latest
    environment: Compile
    steps:
      - name: 📦 Prepate Git Repo
        uses: actions/checkout@v2

      - name: 📦 Install npm
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
          architecture: x64

      - name: 📦 Package Executable
        run: |
          npm run prepare
          npm run make

      - name: 📦 Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: out/

      - name: 🚀 Deploy Installer to Releases
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'out/make/squirrel.windows/x64/*.exe'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy
    needs: make
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: out/desktopflick-win32-x64

      - name: 📦 Zip file
        uses: papeloto/action-zip@v1
        with:
          files: out/desktopflick-win32-x64
          dest: desktopflick-windows.zip

      - name: 🚀 Deploy Binaries to Releases
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'desktopflick-windows.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
