name: npm CI
on: [push, pull_request]

jobs:
  npm_ci:
    name: npm CI
    runs-on: windows-latest
    steps:
      - name: 📦 Prepate Git Repo
        uses: actions/checkout@v2

      - name: 📦 Install npm
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
          architecture: x64

      - name: ✔ Test with npm
        run: |
          npm ci
          npm run prepare
